doskaObyavleniy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/urls.py
from django.urls import path
from .views import index
from .views import other_page
from .views import BBLoginView
from .views import profile
from .views import BBLogoutView
from .views import ChangeUserInfoView
from .views import BBPasswordChangeView
from .views import RegisterDoneView, RegisterUserView
from .views import user_activate
from .views import DeleteUserView


app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('<str:page>/', other_page, name='other'),
    path('account/login', BBLoginView.as_view(),name='login'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('account/logout/', BBLogoutView.as_view(), name='logout'),
    path('account/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal
from .utilities import send_activation_notification
user_registrated = Signal('instance')




class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True,db_index=True, verbose_name='Прошел активацию?')
    send_message = models.BooleanField(default=True,verbose_name='Оповещать при новых комментариях?')

class Meta(AbstractUser.Meta):
    pass

def user_registrated_dispatcher(sender, **kwargs):
   send_activation_notification(kwargs['instance'])


user_registrated.connect(user_registrated_dispatcher)

main/forms.py
from django import forms
from .models import AdvUser
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation
from .models import user_registrated

class ChangeUserInfoForm(forms.ModelForm):
   email = forms.EmailField(required=True, label='Адрес электронной почты')

   class Meta:
       model = AdvUser
       fields = ('username', 'email', 'first_name', 'last_name', 'send_message')


class RegisterUserForm(forms.ModelForm):
   email = forms.EmailField(required=True,
                            label='Адрес электронной почты')
   password1 = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput,
                               help_text=password_validation.password_validators_help_text_html())
   password2 = forms.CharField(label='Пароль (повторно)',
                               widget=forms.PasswordInput,
                               help_text='Повторите тот же самый пароль еще раз')

def clean_password1(self):
       password1 = self.cleaned_data['password1']
       if password1:
           password_validation.validate_password(password1)
       return password1

def clean(self):
       super().clean()
       password1 = self.cleaned_data['password1']
       password2 = self.cleaned_data['password2']
       if password1 and password2 and password1 != password2:
           errors = {'password2': ValidationError(
               'Введенные пароли не совпадают', code='password_mismatch'
           )}
           raise ValidationError(errors)







class RegisterUserForm(forms.ModelForm):
   email = forms.EmailField(required=True,
                            label='Адрес электронной почты')
   password1 = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput,
                               help_text=password_validation.password_validators_help_text_html())
   password2 = forms.CharField(label='Пароль (повторно)',
                               widget=forms.PasswordInput,
                               help_text='Повторите тот же самый пароль еще раз')

   def clean_password1(self):
       password1 = self.cleaned_data['password1']
       if password1:
           password_validation.validate_password(password1)
       return password1

   def clean(self):
       super().clean()
       password1 = self.cleaned_data['password1']
       password2 = self.cleaned_data['password2']
       if password1 and password2 and password1 != password2:
           errors = {'password2': ValidationError(
               'Введенные пароли не совпадают', code='password_mismatch'
           )}
           raise ValidationError(errors)

   def save(self, commit=True):
       user = super().save(commit=False)
       user.set_password(self.cleaned_data['password1'])
       user.is_active = False
       user.is_activated = False
       if commit:
           user.save()
       user_registrated.send(RegisterUserForm, instance=user)
       return user

   class Meta:
       model = AdvUser
       fields = ('username', 'email', 'password1', 'password2',
                 'first_name', 'last_name', 'send_message')

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from .forms import ChangeUserInfoForm
from .models import AdvUser
from django.contrib.auth.views import PasswordChangeView
from django.core.signing import BadSignature
from .utilities import signer
from django.views.generic import UpdateView, CreateView, TemplateView, DeleteView
from django.contrib import messages
from django.contrib.auth import logout



def index(request):
    return render(request, 'main/index.html')


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    template_name = 'main/login.html'


@login_required
def profile(request):
    return render(request, 'main/profile.html')


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin,
                         UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Личные данные пользователя изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin,
                           PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'






from django.views.generic import CreateView

from .forms import RegisterUserForm
class RegisterUserView(CreateView):
   model = AdvUser
   template_name = 'main/Register_user.html'
   form_class = RegisterUserForm
   success_url = reverse_lazy('main:register_done')


from django.views.generic import TemplateView
class RegisterDoneView(TemplateView):
   template_name = 'main/register_done.html'



def user_activate(request, sign):
   try:
       username = signer.unsign(sign)
   except BadSignature:
       return render(request, 'main/bad_signature.html')
   user = get_object_or_404(AdvUser, username=username)
   if user.is_activated:
       template = 'main/user_is_activated.html'
   else:
       template = 'main/activation_done.html'
       user.is_activated = True
       user.is_active = True
       user.save()
   return render(request, template)

class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

main/templates/layout/basic.html
{% load static %} {% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'main/style.css' %}"
    />
    {% bootstrap_css %} {% bootstrap_javascript jquery='slim' %}
    <title>
      {% block title %} Главная {% endblock %} - Электронная доска объявлений
    </title>
  </head>
  <body>
    <div class="container-fluid">
      <div
        class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3 bg-white border-bottom box-shadow"
      >
        <h5 class="mr-md-auto p-2">Электронная доска объявлений</h5>
        {% if user.is_authenticated %}
        <div class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            >Профиль</a
          >
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'main:profile' %}"
              >Мои объявления</a
            >
            <a class="dropdown-item" href="{% url 'main:profile_change' %}"
              >Изменить личные данные</a
            >
            <a class="dropdown-item" href="{% url 'main:password_change' %}"
              >Изменить пароль</a
            >
            <div class="dropdown-divider"></div>
            <form method="post" action="{% url 'main:logout' %}">
              {% csrf_token %}
              <button type="submit" class="dropdown-item">Выйти</button>
            </form>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'main:profile_delete' %}">Удалить</a>
          </div>
        </div>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'main:register' %}">Регистрация</a>
        <a class="p-2 text-dark" href="{% url 'main:login' %}">Вход</a>
        {%endif%}
      </div>

      <div class="row">
        <nav class="col-md-auto nav flex-column">
          <a class="nav-link root" href="{% url 'main:index' %}">Главная</a>
          <a class="nav-link root" href="{% url 'main:other' page='about' %}"
            >О сайте</a
          >
          <span class="nav-link root font-weight-bold">Недвижимость</span>
          <a class="nav-link" href="#">Жилье</a>
          <a class="nav-link" href="#">Склады</a>
          <a class="nav-link" href="#">Квартиры</a>
          <span class="nav-link root font-weight-bold">Транспорт</span>
          <a class="nav-link" href="#">Автомобили</a>
          <a class="nav-link" href="#">Мото</a>
          <a class="nav-link" href="#">Велосипеды</a>
        </nav>

        <div class="container">
          {% bootstrap_messages %} {% block content %} {% endblock %}
        </div>
      </div>

      <footer class="mt-3 border-top">
        <small class="p-2">&copy; Знакомство с фреймворком Django. 2024</small>
      </footer>
    </div>
    <!-- Close container-fluid -->
  </body>
</html>